defmodule AquaSense.Repo.Migrations.AddReadings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:readings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :device_id, :text, null: false
      add :level, :float, null: false
      add :temperature, :float, null: false
      add :conductivity, :float, null: false

      add :read_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:readings)
  end
end
